# Generated by Django 4.0.6 on 2022-09-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.TextField(blank=True, null=True)),
                ('a_img', models.TextField(blank=True, null=True)),
                ('a_date', models.TextField(blank=True, null=True)),
                ('a_address', models.TextField(blank=True, null=True)),
                ('a_price', models.TextField(blank=True, null=True)),
                ('a_organizer', models.TextField(blank=True, null=True)),
                ('a_url', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
